#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Soledad Retamar    #- pon tu nombre en lugar del mio [AQUI+]

# Short bio or description (displayed in the header)

description: Blog para compartir algunos trabajos en R #- pon tu descripcion de lo que quires hacer en el blog [AQUI+]


# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: ../sole_blog/images/meSmall.jpg

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble: 
  email: soledad.retamar@gmail.com           #- put here your e-mail [AQUI+]
  facebook: 
  flickr: 
  github: retamars  #- put here your github account [AQUI+]
  instagram: 
  linkedin: 
  pinterest: 
  rss: Y # just type anything here for a working RSS icon, make sure you set the "url" above!
  twitter: 
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"

# Your disqus shortname, entering this will enable commenting on posts
disqus: 

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: 

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
#url: https://retamars.github.io/sole_blog
# url: https://retamars.github.io
url:
# If you're hosting your site at a Project repository on GitHub pages 
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: https://retamars.github.io/sole_blog/

#
# !! You don't need to change any of the configuration flags below !!
#

markdown: kramdown
#highlighter: pygments
highlighter: rouge
permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.0.0

# Set the Sass partials directory, as we're using @imports
sass:
  sass_dir: _scss
  style: :expanded # You might prefer to minify using :compressed
  #these styles are just for code blocks i think
  #http://web-design-weekly.com/2014/06/15/different-sass-output-styles/

# Use the following plug-ins
gems:
  - jemoji # Emoji please!
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md

theme: jekyll-theme-architect
#theme: jekyll-theme-minimal
