---
layout: post
title: Consejo Superior UTN
author: Soledad Retamar
published: false
status: process
draft: false
tags: consejo
---

Hola a tod@s,

Este post surge del trabajo realizado en el grupo de investigación GIBD, como ejemplo de aplicación de algunas herramientas de minería de texto.
Si les gusta y lo quieren compartir se encuentra todo el código alojado en el repositorio ** / **

- Acuerdate que has de modificar el fichero **_config.yml** para poner tus datos (nombre , e-mail etc...). Lo que tienes que cambiar esta señalado con la marca [AQUI+]   

- Si quieres poner tu foto tienes que sustituir el archivo meSmall.jpg que encontraras en la carpeta  [  /images  ]   


Para subir posts a tu blog solo tienes que añadir ficheros escritos en markdown (.md) en la carpeta [  _posts  ]    


Este blog esta muy-muy basado, vamos que es una copia (forkeo) del de Andy South. Lo puedes ver [aquí](http://andysouth.github.io/)    



Ale, a escribir    



``` {r, eval=FALSE, echo= TRUE}
PD: recuerda que si quieres escribir con ficheros (.Rmd):   

0) Escribe en .Rmd pero el yaml header ha de tener (mira el fichero en la carpeta _rmd):     

    - layout: post    
    
    - status: process  
    
1) Haz un source del fichero rmd2md.R Se cargara la función rmd2md() 

2) En la consola de RStudio ejecuta:  rmd2md()  
  
```


Un poco mejor explicado [aquí](http://perezp44.github.io/r/Tutorial-para-crear-Jekyll-blog-hosted-in-Gitbub/)
